# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FerielApp', '0002_composant_modele_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='profile_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FerielApp.Profile'),
        ),
    ]
