# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FerielApp', '0003_commentaire_profile_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='comment_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
