# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FerielApp', '0005_auto_20170907_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_profile', models.FileField(upload_to='images', verbose_name='Photos')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='image_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FerielApp.Photo'),
        ),
    ]
