# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FerielApp', '0006_auto_20170911_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='communaute',
            name='modele_fk',
            field=models.ManyToManyField(to='FerielApp.Modele'),
        ),
    ]
