# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FerielApp', '0009_auto_20170912_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrique',
            name='modele_fk',
        ),
        migrations.AddField(
            model_name='modele',
            name='rubrique_fk',
            field=models.ManyToManyField(to='FerielApp.Rubrique'),
        ),
    ]
