# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FerielApp', '0010_auto_20170912_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modele',
            name='attributs',
        ),
        migrations.AlterField(
            model_name='modele',
            name='type_m',
            field=models.CharField(choices=[('Conceptual component model', 'Conceptual component model'), ('Software component model', 'Software component model')], max_length=256),
        ),
    ]
